logs:
  access:
    enabled: true
    format: json
    fields:
      general:
        defaultmode: drop
        names:
          StartUTC: keep
          RequestMethod: keep
          RequestPath: keep
          RequestHost: keep
          DownstreamStatus: keep
          Duration: keep
          ServiceName: keep
          RouterName: keep
          ClientHost: keep
          OriginStatus: keep
          OriginDuration: keep
          RetryAttempts: keep
      headers:
        defaultmode: drop
